### ISSUE TITLE
Does not work with SDK restraint  '>=2.16.0 <3.0.0'

### ISSUE THREAD

**Issue by TekExplorer** [NiklasLehnfeld/flutter-android-build-action#1]
It seems like it's using a dev build of 2.15?

 I don't really get it...

Regardless, my workflow doesn't work because of this.

**Comment by TekExplorer** [comment]
doesnt seem like your action is the culprit

**Comment by NiklasLehnfeld** [comment]
Hey @TekExplorer ,
first of all thanks for using my build action. Really appreciate it!
I can highly recommend the [flutter-action](https://github.com/marketplace/actions/flutter-action) to setup the flutter environment in your github workflow as you need it. It's really easy to use.
If you need further help or if you have some improvement suggestions. Let me know :)

**Comment by TekExplorer** [comment]
yep, i found it soon after checking this one out. thanks though!
